### ISSUE TITLE
Sketch not running ArrayIndexOutofBound error

### ISSUE THREAD

**Issue by Electromania** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#14]
Hi,

I am trying to make your sketch run. But when compiled i get following errors

1) Could not run the sketch (Target VM failed to initialize)
2) ArrayIndexOutofBound at line : 205 
  button[p] = new Radio(35, 95+(yPos*20),12,color(180),color(80),color(255),p,button);

can you please help in understanding what is going wrong.
I just downloaded and compiled rightaway.

EM

**Comment by biomurph** [comment]
@Electromania I just made an update to the sketch.
Please download or pull the new code and try it. It should work.

**Comment by Electromania** [comment]
i tried again, no success. attached is the screenshot of screen i see with error. it just freezes the program - i have to End Task to stop it.
![error](https://user-images.githubusercontent.com/16209676/36779288-c2fd10be-1c6f-11e8-943b-9032709509aa.jpg)

**Comment by biomurph** [comment]
The problem is happening when the sketch tries to create a list of serial ports and associated radio buttons to allow you to select the port. The issue may be happening because you don't have many ports on your PC. When you run Arduino and select the Arduino board to program, how many ports do you see in the dropdown menu?

The sketch is adding a radio button in order to place the "Refresh Serial Ports List" selection. Actually, the sketch already refreshes the serial ports automatically, so you don't really need that line.
Try commenting out lines 203 to 206 and see if it works.

**Comment by Electromania** [comment]
thanks, i made it work. apparently it needs some port to be ready to be opened. i was running it without connecting any arduino. 
now at least the program is running : ). i will see how to get the heart beating ; ).

thanks a lot

**Comment by biomurph** [comment]
Oh, yes. You do need to actually have a serial port.
I will post an issue about that and we will see about fixing this edge case.

Happy Heartbeats!
