### ISSUE TITLE
Problemas com a Precisão do sensor

### ISSUE THREAD

**Issue by Klarinemend** [WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer#25]
Precisão do sensor não está muito boa, os dados do sensor dá, não varia muito. O que pode ser feito para resolver isso?
![pulsação](https://user-images.githubusercontent.com/78544421/116950747-56503d80-ac5c-11eb-972b-651a0f7187f5.png)
[https://www.tinkercad.com/login?next=%2Fthings%2FjfoPR4Aoigb-fantabulous-gaaris%2Feditel%3Fsharecode%3D61G4X4tOjOA0T4u6OsugjoI6tvYWOIVzZhZz0n02EDA](url)

**Comment by biomurph** [comment]
@Klarinemend 
My Portuguese is not very good. 
It does look like there is a pulse signal in there somewhere. 
It also looks like you have some very prominent power line noise in the signal as well.
Try running the Pulse Sensor on your computer when you are NOT plugged into the wall outlet. (battery power on the laptop).

Also, please send a picture of your Pulse Sensor, so I can verify that you have legitimate hardware.

**Comment by Klarinemend** [comment]
![image](https://user-images.githubusercontent.com/78544421/117053078-e76ff480-acee-11eb-9bbc-3674564ca142.png)

**Comment by Klarinemend** [comment]
![image](https://user-images.githubusercontent.com/78544421/117053144-ff477880-acee-11eb-86e2-ed06ebeb7895.png)

**Comment by biomurph** [comment]
@Klarinemend 
I'm sorry to say, but you purchased a knockoff of our work.
Since it's a clone, I can't really troubleshoot the hardware for you.
Did you try without connecting your power supply?

Most knockoffs don't work very well. Some do, but it's a gamble.

Please support the original makers of Open Source Hardware  and purchase legit parts from reputable dealers.
We sell at www.pulsesensor.com
Also available at SparkFun and Adafruit.
